import { beforeEach, describe, expect, it } from "vitest"
import { Application } from "@hotwired/stimulus"
import { registerPoetryChartsControllers } from "../../app/javascript/poetry/charts/index.js"
import { cubicBezier, EASINGS, tween } from "../../app/javascript/poetry/charts/motion/tween.js"
import { sectorPath } from "../../app/javascript/poetry/charts/motion/sector.js"

// Phase A-W2: the tween kernel, the sector-path port, and the motion
// controller's polar fan-out. The sector fixtures are generated by the
// RUBY Polar.sector_path (itself recharts' byte-exact port) - the JS port
// must reproduce them byte-for-byte, so mid-sweep paths and server paths
// share one geometry.

const nextFrame = () => new Promise((resolve) => setTimeout(resolve, 0))

// -- rAF under manual control -------------------------------------------

let rafQueue = []
const pump = (now) => {
  const queue = rafQueue
  rafQueue = []
  for (const callback of queue) callback(now)
}

beforeEach(() => {
  rafQueue = []
  globalThis.requestAnimationFrame = (callback) => rafQueue.push(callback)
  globalThis.cancelAnimationFrame = () => {}
  delete globalThis.matchMedia
})

// -- the kernel -----------------------------------------------------------

describe("tween kernel", () => {
  it("solves the CSS cubic-beziers", () => {
    const ease = cubicBezier(0.25, 0.1, 0.25, 1)
    expect(ease(0)).toBe(0)
    expect(ease(1)).toBe(1)
    expect(ease(0.5)).toBeGreaterThan(0.79) // CSS ease(0.5) = 0.8024
    expect(ease(0.5)).toBeLessThan(0.81)
    expect(EASINGS["ease-in"](0.3)).toBeLessThan(0.3)
    expect(EASINGS["ease-out"](0.3)).toBeGreaterThan(0.3)
    expect(EASINGS.linear(0.42)).toBe(0.42)
  })

  it("steps through rAF time, holds the delay, and lands exactly on 1", () => {
    const frames = []
    tween({ duration: 1000, delay: 200, easing: "linear", onFrame: (e) => frames.push(e) })
    pump(0) // establishes the start; still inside the delay
    pump(100) // still inside the delay
    pump(700) // 500ms in -> 0.5
    pump(1200) // 1000ms in -> exactly 1
    expect(frames).toEqual([0.5, 1])
  })

  it("finishes immediately when the duration is zero", () => {
    const frames = []
    let finished = false
    tween({ duration: 0, onFrame: (e) => frames.push(e), onFinish: () => (finished = true) })
    expect(frames).toEqual([1])
    expect(finished).toBe(true)
  })
})

// -- the sector-path port ---------------------------------------------------

// Generated by Poetry::Charts::Polar.sector_path (Ruby) - byte parity.
const SECTOR_FIXTURES = [
  { params: [320, 180, 0, 120, 0, 137.4545], d: "M440,180A120,120,0,0,0,231.5911,98.8589L320,180Z" },
  {
    params: [320, 180, 60, 100, 90, -47.25],
    d: "M320,80A100,100,0,0,1,387.8801,253.4323L360.728,224.0594A60,60,0,0,0,320,120Z",
  },
  {
    params: [320, 180, 60, 100, 0, 360],
    d: "M420,180A100,100,0,1,0,420,180.0017L380,180.001A60,60,0,1,1,380,180Z",
  },
  {
    params: [100.5, 80.25, 20, 45, 210, 273.333],
    d: "M61.5289,102.75A45,45,0,0,0,103.1163,125.1739L101.6628,100.2162A20,20,0,0,1,83.1795,90.25Z",
  },
]

describe("sector path port", () => {
  it("reproduces the Ruby oracle byte-for-byte (incl. the 359.999 full circle)", () => {
    for (const { params, d } of SECTOR_FIXTURES) {
      expect(sectorPath(...params)).toBe(d)
    }
  })
})

// -- the controller ---------------------------------------------------------

const SECTORS = {
  a: { inner: 60, outer: 100, start: 0, end: 240 },
  b: { inner: 60, outer: 100, start: 250, end: 360 }, // 10deg padding gap
}

const markup = ({ animate = true } = {}) => `
  <div data-controller="poetry--charts--motion">
    <svg data-slot="chart-svg" ${animate ? 'data-animate=""' : ""}
         style="--poetry-motion-duration: 1000ms; --poetry-motion-easing: linear; --poetry-motion-delay: 0ms">
      <path id="a" data-motion-sector="320 180 60 100 0 240" data-motion-group="pie-0" d="SERVER_D_A"></path>
      <path id="b" data-motion-sector="320 180 60 100 250 360" data-motion-group="pie-0" d="SERVER_D_B"></path>
    </svg>
  </div>`

async function boot(html) {
  document.body.innerHTML = html
  const application = Application.start()
  registerPoetryChartsControllers(application)
  await nextFrame()
  return application
}

describe("poetry--charts--motion", () => {
  let application

  beforeEach(() => async () => {
    application?.stop()
    document.body.replaceChildren()
    await nextFrame()
  })

  it("fans the sectors out with recharts' accumulator and restores the server d", async () => {
    application = await boot(markup())
    const svg = document.querySelector("svg")
    const a = document.getElementById("a")
    const b = document.getElementById("b")

    // The entrance state applies synchronously - both sectors collapsed.
    expect(svg.getAttribute("data-motion")).toBe("entrance")
    expect(a.getAttribute("d")).toBe(sectorPath(320, 180, 60, 100, 0, 0))
    expect(b.getAttribute("d")).toBe(sectorPath(320, 180, 60, 100, 10, 10))

    pump(0)
    pump(500) // linear 0.5: a sweeps 120deg; b starts after a's end + the 10deg pad
    expect(a.getAttribute("d")).toBe(sectorPath(320, 180, 60, 100, 0, 120))
    expect(b.getAttribute("d")).toBe(sectorPath(320, 180, 60, 100, 130, 185))

    pump(1000) // the final frame restores the exact server-rendered paths
    expect(a.getAttribute("d")).toBe("SERVER_D_A")
    expect(b.getAttribute("d")).toBe("SERVER_D_B")
    expect(svg.getAttribute("data-motion")).toBe("settled")
  })

  it("settles immediately under prefers-reduced-motion with the server d untouched", async () => {
    globalThis.matchMedia = () => ({ matches: true })
    application = await boot(markup())

    expect(document.querySelector("svg").getAttribute("data-motion")).toBe("settled")
    expect(document.getElementById("a").getAttribute("d")).toBe("SERVER_D_A")
    expect(rafQueue.length).toBe(0)
  })

  it("settles immediately when animation is off", async () => {
    application = await boot(markup({ animate: false }))

    expect(document.querySelector("svg").getAttribute("data-motion")).toBe("settled")
    expect(document.getElementById("a").getAttribute("d")).toBe("SERVER_D_A")
  })

  it("settles cartesian charts without sectors (no getAnimations in jsdom)", async () => {
    application = await boot(`
      <div data-controller="poetry--charts--motion">
        <svg data-slot="chart-svg" data-animate="" style="--poetry-motion-duration: 400ms">
          <path data-slot="chart-bar" d="M0,0"></path>
        </svg>
      </div>`)

    expect(document.querySelector("svg").getAttribute("data-motion")).toBe("settled")
  })
})

// -- the cross-render morph (A-W3) --------------------------------------

const morphMarkup = (d, cx, cy) => `
  <div data-chart="chart-morph">
    <div data-controller="poetry--charts--motion">
      <svg data-slot="chart-svg" data-animate=""
           style="--poetry-motion-duration: 1000ms; --poetry-motion-easing: linear; --poetry-motion-delay: 0ms">
        <path data-slot="chart-line" data-key="desktop" d="${d}"></path>
        <circle data-slot="chart-dot" data-key="desktop" cx="${cx}" cy="${cy}" r="3"></circle>
      </svg>
    </div>
  </div>`

describe("poetry--charts--motion morph", () => {
  let application

  beforeEach(() => async () => {
    application?.stop()
    document.body.replaceChildren()
    await nextFrame()
  })

  it("FLIPs a same-id re-render from the old geometry to the new", async () => {
    application = await boot(morphMarkup("M0,100L50,50L100,80", 10, 20))
    expect(document.querySelector("svg").getAttribute("data-motion")).toBe("settled")

    // The server re-render: same chart id, same structure, new values.
    document.body.innerHTML = morphMarkup("M0,60L50,90L100,20", 30, 40)
    await nextFrame()

    const svg = document.querySelector("svg")
    const path = document.querySelector("path")
    const dot = document.querySelector("circle")

    // The FLIP applied synchronously: the new render shows the OLD geometry.
    expect(svg.getAttribute("data-motion")).toBe("morph")
    expect(path.getAttribute("d")).toBe("M0,100L50,50L100,80")
    expect(dot.getAttribute("cx")).toBe("10")

    pump(0)
    pump(500) // linear 0.5: numbers halfway
    expect(path.getAttribute("d")).toBe("M0,80L50,70L100,50")
    expect(dot.getAttribute("cx")).toBe("20")
    expect(dot.getAttribute("cy")).toBe("30")

    pump(1000) // exact new server strings restored
    expect(path.getAttribute("d")).toBe("M0,60L50,90L100,20")
    expect(dot.getAttribute("cx")).toBe("30")
    expect(svg.getAttribute("data-motion")).toBe("settled")
  })

  it("falls back to the entrance replay when the structure changes", async () => {
    application = await boot(morphMarkup("M0,100L50,50L100,80", 10, 20))

    // Fewer points -> different skeleton -> no morph; jsdom cartesian
    // entrance settles immediately with the new server d untouched.
    document.body.innerHTML = morphMarkup("M0,60L50,90", 30, 40)
    await nextFrame()

    expect(document.querySelector("svg").getAttribute("data-motion")).toBe("settled")
    expect(document.querySelector("path").getAttribute("d")).toBe("M0,60L50,90")
  })

  it("never morphs under prefers-reduced-motion", async () => {
    application = await boot(morphMarkup("M0,100L50,50L100,80", 10, 20))

    globalThis.matchMedia = () => ({ matches: true })
    document.body.innerHTML = morphMarkup("M0,60L50,90L100,20", 30, 40)
    await nextFrame()

    expect(document.querySelector("svg").getAttribute("data-motion")).toBe("settled")
    expect(document.querySelector("path").getAttribute("d")).toBe("M0,60L50,90L100,20")
  })
})
