# frozen_string_literal: true

require "json"

module Poetry
  module Charts
    module Geometry
      # Loader for the d3 oracle fixtures - every expected value was
      # generated by the REAL d3 packages (test/support/
      # generate_geometry_fixtures.mjs), so these tests compare the Ruby
      # ports against ground truth, not our own reading of the source.
      module FixturesHelper
        def fixtures
          @fixtures ||= JSON.parse(
            File.read(Poetry::Charts.root.join("test/fixtures/geometry_fixtures.json"))
          )
        end

        # Exact by default (the ports share IEEE-754 arithmetic with JS);
        # the assertion names the case for forensics when a port drifts.
        def assert_numbers_equal(expected, actual, label)
          assert_equal expected.length, actual.length, "#{label}: length"
          expected.zip(actual).each_with_index do |(want, got), i|
            if want.nil?
              refute_predicate got, :finite?, "#{label}[#{i}]: JS produced non-finite (null in JSON)"
            else
              assert_equal want, got, "#{label}[#{i}]"
            end
          end
        end
      end
    end
  end
end
