# frozen_string_literal: true

module Poetry
  module Charts
    # The geometry core (N10 W2): faithful Ruby ports of the exact math the
    # shadcn charts stand on - d3-array ticks, d3-scale linear/band/point,
    # d3-shape line/area/curves/stack (the modules recharts vendors), and
    # recharts' decimal-exact nice-ticks. Every port is oracle-tested:
    # d3 behavior against fixtures generated by the REAL d3 packages
    # (test/support/generate_geometry_fixtures.mjs), recharts behavior
    # against its own translated spec cases.
    #
    # JS number semantics are part of the contract - path strings must match
    # d3-shape byte-for-byte - so rounding and stringification go through
    # js_round / js_number below, never through Ruby defaults (Ruby rounds
    # half away from zero and prints "80.0"; JS floors x+0.5 and prints "80").
    module Geometry
      module_function

      # JS Math.round: floor(x + 0.5) - differs from Float#round at negative
      # halves (JS rounds -2.5 to -2; Ruby to -3).
      def js_round(value)
        (value + 0.5).floor
      end

      # JS Number#toString for the values that appear in SVG path data:
      # integral doubles print bare ("80", not "80.0"), -0 prints "0", and
      # everything else uses shortest round-trip decimal (Ruby and V8 agree
      # on shortest-repr in the post-rounding magnitude range; the exponent
      # guard covers the sub-1e-4 corner where Ruby switches early).
      def js_number(value)
        return "0" if value.zero?

        integral = value.to_i
        return integral.to_s if value == integral

        text = value.to_s
        return text unless text.include?("e")

        format("%.12f", value).sub(/0+\z/, "").delete_suffix(".")
      end

      # JS truthiness for the curve state machines (_line is undefined | 0 |
      # 1 | NaN in d3-shape): nil, 0, and NaN are falsy.
      def js_truthy?(value)
        return false if value.nil?
        return false if value.is_a?(Float) && value.nan?

        value != 0
      end
    end
  end
end

require_relative "geometry/ticks"
require_relative "geometry/nice_ticks"
require_relative "geometry/scale/linear"
require_relative "geometry/scale/band"
require_relative "geometry/path"
require_relative "geometry/curve"
require_relative "geometry/line"
require_relative "geometry/area"
require_relative "geometry/stack"
